# Generated by Django 3.2.7 on 2021-09-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_dep', models.CharField(max_length=20)),
                ('staff_mobileno', models.IntegerField()),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
    ]
